version: "3.7"

services:
  api:
    image: rafaellevissa/company-python:latest
    deploy:
      replicas: 3
    secrets:
      - company-python
    environment:
      - FLASK_ENV=production
      - FLASK_APP=server.py
    ports:
      - 5000:5000

