version: "3.5"

services:
  db:
    image: mysql
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
  
  api:
    build: ./
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db