version: "3.7"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=desafio-python
    env_file:
      - .env

  api:
    build: ./
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
