version: "3.7"

services:
  api:
    build: ./
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    env_file:
      - .env
