"""create user

Revision ID: f94bb52a5655
Revises: cb63dd8dfd8a
Create Date: 2023-07-27 12:18:39.897875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table
from utils.bcrypt import hash_password
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'f94bb52a5655'
down_revision = 'cb63dd8dfd8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    hashed_password = hash_password("123Change@")
    users_table = table('users',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('email', sa.String),
        sa.Column('password', sa.String),
        sa.Column('created_at', sa.DateTime)
    )

    op.bulk_insert(
        users_table,
        [
            {'name': 'admin', 'email': 'admin@email.com', 'password': hashed_password}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
